accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup/', views.SignUp.as_view(), name = 'signup'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new/', views.CreatePost.as_view(), name = 'create'),
    path('by/<username>/', views.UserPosts.as_view(), name = 'for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name = 'single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name = 'delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name = 'test'),
    path('thanks/', views.ThanksPage.as_view(), name = 'thanks'),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('groups/', include('groups.urls', namespace = 'groups')),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Social Media</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

	<!-- Google Material Design Icons -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	  
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark mynav" role="navigation" id="navbar">
		<div class="container">
			<!-- Brand -->
			<a class="navbar-brand mynav" href="{% url 'home' %}">Social Media</a>
			
			<!-- Right Navbar -->
			<div class="collapse navbar-collapse">
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav">
						<li class="nav-item"><a class="nav-link" href="https://github.com/kennethalberto/social-media-project">Github</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'posts:all' %}">Posts</a></li>
					</ul>

					<div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
						<ul class="navbar-nav ml-auto">
							{% if user.is_authenticated %}
								<li class="nav-item"><a class="nav-link" href="{% url 'posts:create' %}">Create Post</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'groups:create' %}">Create Group</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
							{% else %}
								<li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
							{% endif %}
						</ul>
					</div>
				</div>
			</div>
		</div>
    </nav>

	<div class="container">
		{% block content %}
		{% endblock %}
	</div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Social Media!</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>You are now logged in</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}